development:
  adapter: postgresql
  encoding: unicode
  database: casetracker_develop
  username: postgres
  password: postgres
  host: db
  pool: 5
  port: 5432


test:
  adapter: postgresql
  encoding: unicode
  database: casetracker_test
  pool: 5
  username: postgres
  password: postgres
  host: db
  port: 5432
  timeout: 5000

production:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV["DB_DATABASE"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] || "localhost" %>
